# circuitbreaker 설정
resilience4j:
  circuitbreaker:
    instances:
      defaultCircuitBreaker:
        slidingWindowSize: 100
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      defaultCircuitBreaker:
        timeoutDuration: 60s
# gateway routes 설정
spring:
  cloud:
    gateway:
      default-filters: # 모든 라우팅에 적용되는 global 필터
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - CircuitBreaker=defaultCircuitBreaker
        - name: LoggingFilter
          args:
            preLogger: true
            postLogger: true
      routes:
        ########## Auths Routes start ##########
        # 사용자 로그인
        - id: user/login
          uri: ${AUTHS_URL}
          predicates:
            - Path=/fassto-admin/api/v1/user/login
            - Method=POST
        ########## Auths Routes end ##########

        ########## Management Routes start ##########
        # 파일 업로드 목록 조회 / 파일 업로드 완료
        - id: management/file-manage/upload/{fileManageCd}
          uri: ${MANAGEMENT_URL}
          predicates:
            - Path=/management/file-manage/upload/{fileManageCd}
            - Method=GET, POST
          filters:
            - name: AuthenticationFilter
              args:
                allow-roles:
                  - ADMIN
                  - CS
                  - MARKETING
                  - SALES
                  - SETTLE
        # preSignedUrl 요청
        - id: management/file-manage/pre-signed-url/{fileManageCd}
          uri: ${MANAGEMENT_URL}
          predicates:
            - Path=/management/file-manage/pre-signed-url/{fileManageCd}
            - Method=GET
          filters:
            - name: AuthenticationFilter
              args:
                allow-roles:
                  - ADMIN
                  - CS
                  - MARKETING
                  - SALES
                  - SETTLE
        # 파일 업로드 수정 / 삭제
        - id: management/file-manage/upload/{fileManageCd}/{fileSeq}
          uri: ${MANAGEMENT_URL}
          predicates:
            - Path=/management/file-manage/upload/{fileManageCd}/{fileSeq}
            - Method=PUT, DELETE
          filters:
            - name: AuthenticationFilter
              args:
                allow-roles:
                  - ADMIN
                  - CS
                  - MARKETING
                  - SALES
                  - SETTLE
        ########## Management Routes end ##########
