server:
  port: 9999

spring:
  application:
    name: spring-cloud-gateway
  profiles:
    default: local
    include:
      - gateway
  main:
    banner-mode: off
  jwt:
    secret-key: "jwt.token.secret"
  # 가상스레드 활성화
  threads:
    virtual:
      enabled: true
# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    gateway:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
# swagger 설정
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    urls:
      - url: ${AUTHS_SWAGGER_DOMAIN}/v3/api-docs
        name: Auths
      - url: ${MANAGEMENT_SWAGGER_DOMAIN}/v3/api-docs
        name: Management
